In [1]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in ./myenv/lib/python3.8/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./myenv/lib/python3.8/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./myenv/lib/python3.8/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in ./myenv/lib/python3.8/site-packages (from pandas) (2024.2)
Requirement already satisfied: numpy>=1.20.3 in ./myenv/lib/python3.8/site-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in ./myenv/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in ./myenv/lib/python3.8/site-packages (1.24.4)

In [269]:
import pandas as pd
import numpy as np
import re

In [270]:
import os
print(os.getcwd())

/Users/francescaparrella

In [16]:
#data cleaning nba22_pergame_stats
data1=pd.read_csv('/Users/francescaparrella/analysis_projects/nba/nba22_pergame_stats.csv')
data1

,Player,Age,Team,Games,Rebounds,Assists,Steals,Points per game
0,Joel Embiid,28.0,PHI,66.0,10.2,4.2,1.0,33.1
1,Luka DonÄiÄ,23.0,DAL,66.0,8.6,8.0,1.4,32.4
2,Damian Lillard,32.0,POR,58.0,4.8,7.3,0.9,32.2
3,Shai Gilgeous-Alexander,24.0,OKC,68.0,4.8,5.5,1.6,31.4
4,Giannis Antetokounmpo,28.0,MIL,63.0,11.8,5.7,0.8,31.1
...,...,...,...,...,...,...,...,...
675,Deonte Burton,29.0,SAC,2.0,0.0,0.0,0.0,0.0
676,Michael Foster Jr.,20.0,PHI,1.0,0.0,0.0,0.0,0.0
677,Frank Jackson,24.0,UTA,1.0,2.0,1.0,0.0,0.0
678,Alondes Williams,23.0,BRK,1.0,1.0,0.0,0.0,0.0
679,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 680 entries, 0 to 679
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player           680 non-null    object
 1   Age              679 non-null    float64
 2   Team             679 non-null    object
 3   Games            679 non-null    float64
 4   Rebounds         679 non-null    float64
 5   Assists          679 non-null    float64
 6   Steals           679 non-null    float64
 7   Points per game  679 non-null    float64
dtypes: float64(6), object(2)
memory usage: 42.6+ KB

In [21]:
#checking dupolicates
dupl=data1[data1.duplicated(subset=['Player'])]
print(dupl)

               Player   Age Team  Games  Rebounds  Assists  Steals  \
8        Kevin Durant  34.0  BRK   39.0       6.7      5.3     0.8
9        Kevin Durant  34.0  PHO    8.0       6.4      3.5     0.3
14       Kyrie Irving  30.0  BRK   40.0       5.1      5.3     1.0
15       Kyrie Irving  30.0  DAL   20.0       5.0      6.0     1.3
58      Mikal Bridges  26.0  PHO   56.0       4.3      3.6     1.2
..                ...   ...  ...    ...       ...      ...     ...
623      Nerlens Noel  28.0  BRK    3.0       3.0      1.0     1.0
625        Davon Reed  27.0  DEN   35.0       1.6      0.5     0.4
626        Davon Reed  27.0  LAL    8.0       0.5      0.5     0.3
653  Ryan Arcidiacono  28.0  NYK   11.0       0.4      0.2     0.2
654  Ryan Arcidiacono  28.0  POR    9.0       1.2      2.3     0.3

     Points per game
8               29.7
9               26.0
14              27.1
15              27.0
58              17.2
..               ...
623              1.0
625              2.3
626              1.0
653              0.3
654              2.6

[140 rows x 8 columns]

In [23]:
#checking null values
data1.isnull()
missing_values = data1.isnull().sum()
print(missing_values)

Player             0
Age                1
Team               1
Games              1
Rebounds           1
Assists            1
Steals             1
Points per game    1
dtype: int64

In [24]:
rows_with_nan = data1[data1.isnull().any(axis=1)]
print(rows_with_nan)

             Player  Age Team  Games  Rebounds  Assists  Steals  \
679  League Average  NaN  NaN    NaN       NaN      NaN     NaN

     Points per game
679              NaN

In [25]:
#handling nulla values
data1.drop(index=679, axis=0, inplace=True)
print('did it')

did it

In [33]:
#checking format name players
pattern = re.compile(r'[^a-zA-Z0-9\s\-\']')
players_with_strange_chars = data1[data1['Player'].apply(lambda x: bool(pattern.search(x)))]
print(players_with_strange_chars)

                   Player   Age Team  Games  Rebounds  Assists  Steals  \
1           Luka DonÄiÄ  23.0  DAL   66.0       8.6      8.0     1.4
28          Nikola JokiÄ  27.0  DEN   69.0      11.8      9.8     1.3
35   Kristaps PorziÅÄ£is  27.0  WAS   65.0       8.4      2.7     0.9
40      Bojan BogdanoviÄ  33.0  DET   59.0       3.8      2.6     0.6
56        Kelly Oubre Jr.  27.0  CHO   48.0       5.2      1.1     1.4
..                    ...   ...  ...    ...       ...      ...     ...
619        Ron Harper Jr.  22.0  TOR    9.0       0.8      0.4     0.0
632    Vince Williams Jr.  22.0  MEM   15.0       1.0      0.3     0.4
651     Wendell Moore Jr.  21.0  MIN   29.0       0.6      0.6     0.3
671      Vernon Carey Jr.  21.0  WAS   11.0       1.0      0.3     0.2
676    Michael Foster Jr.  20.0  PHI    1.0       0.0      0.0     0.0

     Points per game
1               32.4
28              24.5
35              23.2
40              21.6
56              20.3
..               ...
619              2.2
632              2.0
651              1.4
671              0.5
676              0.0

[65 rows x 8 columns]

In [34]:
data1['Player'] = data1['Player'].str.replace('Ä', 'c')
print(data1[data1['Player'].str.contains('c')])

                 Player   Age Team  Games  Rebounds  Assists  Steals  \
1         Luka Doncic  23.0  DAL   66.0       8.6      8.0     1.4
11     Donovan Mitchell  26.0  CLE   68.0       4.3      4.4     1.5
24          Zach LaVine  27.0  CHI   77.0       4.5      4.2     0.9
28        Nikola Jokic  27.0  DEN   69.0      11.8      9.8     1.3
29        Pascal Siakam  28.0  TOR   71.0       7.8      5.8     0.9
..                  ...   ...  ...    ...       ...      ...     ...
663        Malcolm Hill  27.0  CHI    5.0       0.6      0.0     0.0
668      Justin Jackson  27.0  BOS   23.0       0.7      0.4     0.2
669     Marko Simonovic  23.0  CHI    7.0       0.3      0.0     0.0
676  Michael Foster Jr.  20.0  PHI    1.0       0.0      0.0     0.0
677       Frank Jackson  24.0  UTA    1.0       2.0      1.0     0.0

     Points per game
1               32.4
11              28.3
24              24.8
28              24.5
29              24.2
..               ...
663              1.0
668              0.9
669              0.9
676              0.0
677              0.0

[148 rows x 8 columns]

In [45]:
data1['Player'] = data1['Player'].str.replace('Luka Donc ic', 'Luka Doncic', regex=False)
print(data1[data1['Player'].str.contains('Luka Doncic')])

         Player   Age Team  Games  Rebounds  Assists  Steals  Points per game
1  Luka Doncic  23.0  DAL   66.0       8.6      8.0     1.4             32.4

In [50]:
data1['Player']=data1['Player'].str.replace('\u00A0',' ')

# Function to clean player names
def clean_player_name(name):
    # Replace specific unwanted characters
    name = name.replace('Ä', 'c')  # Example of replacing 'Ä' with 'c'
    # Remove any special characters using regex
    name = re.sub(r'[^\w\s]', '', name)  # This removes all non-word characters except spaces
    return name

# Apply the cleaning function to the 'Player' column
data1['Player'] = data1['Player'].apply(clean_player_name)

# Also strip any leading or trailing whitespace
data1['Player'] = data1['Player'].str.strip()

In [75]:
duplicates = data1.loc[data1['Player'] == 'Dyson Daniels']
print(duplicates)

            Player   Age Team  Games  Rebounds  Assists  Steals  \
534  Dyson Daniels  19.0  NOP   59.0       3.2      2.3     0.7

     Points per game
534              3.8

In [139]:
#data cleaning nba22_advanced_stats
data2=pd.read_csv('/Users/francescaparrella/analysis_projects/nba/nba22_advanced_stats_new.csv')
data2

,Player,Age,Team,Player Efficiency,True Shooting,Win Shares,BPM
0,Precious Achiuwa,23,TOR,15.2,0.554,2.2,-2.3
1,Steven Adams,29,MEM,17.5,0.564,3.4,0.6
2,Bam Adebayo,25,MIA,20.1,0.592,7.4,1.5
3,Ochai Agbaji,22,UTA,9.5,0.561,1.3,-3.0
4,Santi Aldama,22,MEM,13.9,0.591,4.6,0.5
...,...,...,...,...,...,...,...
674,Thaddeus Young,34,TOR,14.1,0.573,1.8,0.1
675,Trae Young,24,ATL,22.0,0.573,6.7,3.3
676,Omer Yurtseven,24,MIA,16.7,0.675,0.3,-3.9
677,Cody Zeller,30,MIA,16.4,0.659,0.7,-2.8
678,Ivica Zubac,25,LAC,16.7,0.661,6.7,-0.9

In [140]:
#checking format name players
pattern = re.compile(r'[^a-zA-Z0-9\s\-\']')
players_with_strange_chars_before = data2[data2['Player'].apply(lambda x: bool(pattern.search(x)))]
print(players_with_strange_chars_before)

                   Player  Age Team  Player Efficiency  True Shooting  \
23    Patrick Baldwin Jr.   20  GSW               11.3          0.546
49        DÄvis BertÄns   30  DAL               11.9          0.618
62     Bogdan BogdanoviÄ   30  ATL               14.2          0.586
63      Bojan BogdanoviÄ   33  DET               17.4          0.627
67     Brandon Boston Jr.   21  LAC               13.4          0.515
..                    ...  ...  ...                ...            ...
633           T.J. Warren   29  PHO               11.6          0.473
634  Duane Washington Jr.   22  PHO                9.3          0.458
635       P.J. Washington   24  CHO               12.9          0.542
636   TyTy Washington Jr.   21  HOU                7.5          0.432
662    Vince Williams Jr.   22  MEM                3.9          0.367

     Win Shares  BPM
23          0.1 -2.1
49          0.9 -1.2
62          2.8  0.5
63          3.5  0.8
67          0.2 -2.2
..          ...  ...
633         0.3 -1.9
634        -0.5 -4.6
635         2.6 -1.3
636        -0.1 -6.3
662        -0.1 -8.5

[66 rows x 7 columns]

In [141]:
data2['Player'] = data2['Player'].str.replace('Ä', 'c')
print(data2[data2['Player'].str.contains('c')])

                       Player  Age Team  Player Efficiency  True Shooting  \
0            Precious Achiuwa   23  TOR               15.2          0.554
3                Ochai Agbaji   22  UTA                9.5          0.561
5    Nickeil Alexander-Walker   24  TOT               11.6          0.565
6    Nickeil Alexander-Walker   24  UTA               13.0          0.609
7    Nickeil Alexander-Walker   24  MIN                9.6          0.503
..                        ...  ...  ...                ...            ...
658          Kenrich Williams   28  OKC               14.4          0.585
660          Patrick Williams   21  CHI               11.2          0.576
662        Vince Williams Jr.   22  MEM                3.9          0.367
672        McKinley Wright IV   24  DAL               12.4          0.536
678               Ivica Zubac   25  LAC               16.7          0.661

     Win Shares  BPM
0           2.2 -2.3
3           1.3 -3.0
5           1.1 -0.9
6           0.8  0.5
7           0.3 -3.0
..          ...  ...
658         3.3  0.5
660         3.5 -1.3
662        -0.1 -8.5
672         0.5 -2.7
678         6.7 -0.9

[148 rows x 7 columns]

In [145]:
unwanted_car=['.']

for char in unwanted_car: #i'm using a loop to iterate unwanted_car and format player for consistency
    data2.loc[:,'Player'] = data2['Player'].str.replace(char, '',regex=False)

In [147]:
#checking null values
data2.isnull()
missing_values = data2.isnull().sum()
print(missing_values)

Player               0
Age                  0
Team                 0
Player Efficiency    0
True Shooting        3
Win Shares           0
BPM                  0
dtype: int64

In [148]:
rows_with_nan = data2[data2.isnull().any(axis=1)]
print(rows_with_nan)

                Player  Age Team  Player Efficiency  True Shooting  \
89         Moses Brown   23  BRK               -2.6            NaN
196  Michael Foster Jr   20  PHI                0.0            NaN
652   Alondes Williams   23  BRK              -20.9            NaN

     Win Shares   BPM
89          0.0  -9.9
196         0.0  -9.2
652        -0.1 -26.5

In [93]:
data2.drop(index=1414, axis=0, inplace=True)
print('did it')

did it

In [150]:
data2.dtypes

Player                object
Age                    int64
Team                  object
Player Efficiency    float64
True Shooting        float64
Win Shares           float64
BPM                  float64
dtype: object

In [110]:
#data cleaning nba22_draft_picks
df_rookie_bef=pd.read_csv('/Users/francescaparrella/analysis_projects/nba/nba22_draft_picks.csv')
df_rookie_bef
df_rookie=df_rookie_bef.loc[:29]

In [115]:
#handling format name players
unwanted_car=['~','+','.']

for char in unwanted_car: #i'm using a loop to iterate unwanted_car and format player for consistency
    df_rookie.loc[:,'Player'] = df_rookie['Player'].str.replace(char, '',regex=False)

In [119]:
df_rookie.loc[:,'Player'] = df_rookie['Player'].str.replace('ć', 'c')
print(df_rookie[df_rookie['Player'].str.contains('c')])

    Round  Pick              Player    Nationality
0       1   1.0      Paolo Banchero  United States
5       1   6.0  Bennedict Mathurin         Canada
8       1   9.0       Jeremy Sochan         Poland
13      1  14.0        Ochai Agbaji  United States
23      1  24.0    MarJon Beauchamp  United States
26      1  27.0        Nikola Jovic         Serbia
27      1  28.0  Patrick Baldwin Jr  United States

In [121]:
df_rookie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Round        30 non-null     int64
 1   Pick         30 non-null     float64
 2   Player       30 non-null     object
 3   Nationality  30 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ KB

In [123]:
#Filtering data1 (nba22_pergame_stats) with draft picks df
filtered_data= data1[data1['Player'].isin(df_rookie['Player'])]
#Merging filterd data with draft picks df to have the same 'player' column and add all the other columns of the df
nba22_pergame_rookie=filtered_data.merge(df_rookie, on='Player', how='left')

In [126]:
nba22_pergame_rookie.head()

,Player,Age,Team,Games,Rebounds,Assists,Steals,Points per game,Round,Pick,Nationality
0,Paolo Banchero,20.0,ORL,72.0,6.9,3.7,0.8,20.0,1,1.0,United States
1,Bennedict Mathurin,20.0,IND,78.0,4.1,1.5,0.6,16.7,1,6.0,Canada
2,Jaden Ivey,20.0,DET,74.0,3.9,5.2,0.8,16.3,1,5.0,United States
3,Jalen Williams,21.0,OKC,75.0,4.5,3.3,1.4,14.1,1,12.0,United States
4,Jabari Smith Jr,19.0,HOU,79.0,7.2,1.3,0.5,12.8,1,3.0,United States

In [132]:
#Adjust little problems in the df: transform age from float to int, put Nationality after Player
nba22_pergame_rookie['Age'] = nba22_pergame_rookie['Age'].astype(int)

cols=nba22_pergame_rookie.columns.tolist()

#df.columns.tolist(): Gets the list of all columns in the DataFrame, 
#cols.index('Player') + 1: Finds the index of the 'Player' column and determines where 'Nationality' should go (right after).
#cols.pop(cols.index('Nationality')): Removes the 'Nationality' column from its original position and stores it.
#cols.insert(): Inserts the 'Nationality' column right after 'Player' in the list.
#df[cols]: Reorders the DataFrame based on the new column order.
cols.insert(cols.index('Player') + 1, cols.pop(cols.index('Nationality')))
nba22_pergame_rookie=nba22_pergame_rookie[cols]

In [138]:
nba22_pergame_rookie.head(20)

,Player,Nationality,Age,Team,Games,Rebounds,Assists,Steals,Points per game,Round,Pick
0,Paolo Banchero,United States,20,ORL,72.0,6.9,3.7,0.8,20.0,1,1.0
1,Bennedict Mathurin,Canada,20,IND,78.0,4.1,1.5,0.6,16.7,1,6.0
2,Jaden Ivey,United States,20,DET,74.0,3.9,5.2,0.8,16.3,1,5.0
3,Jalen Williams,United States,21,OKC,75.0,4.5,3.3,1.4,14.1,1,12.0
4,Jabari Smith Jr,United States,19,HOU,79.0,7.2,1.3,0.5,12.8,1,3.0
5,Keegan Murray,United States,22,SAC,80.0,4.6,1.2,0.8,12.2,1,4.0
6,Jeremy Sochan,Poland,19,SAS,56.0,5.3,2.5,0.8,11.0,1,9.0
7,Malaki Branham,United States,19,SAS,66.0,2.7,1.9,0.5,10.2,1,20.0
8,Shaedon Sharpe,Canada,19,POR,80.0,3.0,1.2,0.5,9.9,1,7.0
9,Tari Eason,United States,21,HOU,82.0,6.0,1.1,1.2,9.3,1,17.0
10,Walker Kessler,United States,21,UTA,74.0,8.4,0.9,0.4,9.2,1,22.0
11,Jalen Duren,United States,19,DET,67.0,8.9,1.1,0.7,9.1,1,13.0
12,Mark Williams,United States,21,CHO,43.0,7.1,0.4,0.7,9.0,1,15.0
13,AJ Griffin,United States,19,ATL,72.0,2.1,1.0,0.6,8.9,1,16.0
14,Ochai Agbaji,United States,22,UTA,59.0,2.1,1.1,0.3,7.9,1,14.0
15,David Roddy,United States,21,MEM,70.0,2.8,0.8,0.4,6.7,1,23.0
16,Johnny Davis,United States,20,WAS,28.0,2.3,1.0,0.4,5.8,1,10.0
17,Nikola Jovic,Serbia,19,MIA,15.0,2.1,0.7,0.5,5.5,1,27.0
18,MarJon Beauchamp,United States,22,MIL,52.0,2.2,0.7,0.4,5.1,1,24.0
19,Blake Wesley,United States,19,SAS,37.0,2.2,2.7,0.7,5.0,1,25.0

In [151]:
#Filtering data2 (nba22_advanced_stats) with draft picks df
filtered_data2= data2[data2['Player'].isin(df_rookie['Player'])]
#Merging filterd data with draft picks df to have the same 'player' column and add all the other columns of the df
nba22_advanced_rookie=filtered_data2.merge(df_rookie, on='Player', how='left')

In [152]:
nba22_advanced_rookie.head()

,Player,Age,Team,Player Efficiency,True Shooting,Win Shares,BPM,Round,Pick,Nationality
0,Ochai Agbaji,22,UTA,9.5,0.561,1.3,-3.0,1,14.0,United States
1,Patrick Baldwin Jr,20,GSW,11.3,0.546,0.1,-2.1,1,28.0,United States
2,Paolo Banchero,20,ORL,14.9,0.529,2.4,-1.5,1,1.0,United States
3,MarJon Beauchamp,22,MIL,8.2,0.513,0.4,-4.8,1,24.0,United States
4,Malaki Branham,19,SAS,9.5,0.524,-0.1,-5.2,1,20.0,United States

In [153]:
#Adjust little problems in the df: put Nationality after Player
cols=nba22_advanced_rookie.columns.tolist()
cols.insert(cols.index('Player') + 1, cols.pop(cols.index('Nationality')))
nba22_advanced_rookie=nba22_advanced_rookie[cols]

In [154]:
nba22_advanced_rookie.head()

,Player,Nationality,Age,Team,Player Efficiency,True Shooting,Win Shares,BPM,Round,Pick
0,Ochai Agbaji,United States,22,UTA,9.5,0.561,1.3,-3.0,1,14.0
1,Patrick Baldwin Jr,United States,20,GSW,11.3,0.546,0.1,-2.1,1,28.0
2,Paolo Banchero,United States,20,ORL,14.9,0.529,2.4,-1.5,1,1.0
3,MarJon Beauchamp,United States,22,MIL,8.2,0.513,0.4,-4.8,1,24.0
4,Malaki Branham,United States,19,SAS,9.5,0.524,-0.1,-5.2,1,20.0

In [155]:
nba22_rookie_stats=pd.merge(nba22_pergame_rookie, nba22_advanced_rookie, on=['Age','Player','Team','Nationality'], how='outer')
print(nba22_rookie_stats)

                Player    Nationality  Age Team  Games  Rebounds  Assists  \
0       Paolo Banchero  United States   20  ORL   72.0       6.9      3.7
1   Bennedict Mathurin         Canada   20  IND   78.0       4.1      1.5
2           Jaden Ivey  United States   20  DET   74.0       3.9      5.2
3       Jalen Williams  United States   21  OKC   75.0       4.5      3.3
4      Jabari Smith Jr  United States   19  HOU   79.0       7.2      1.3
5        Keegan Murray  United States   22  SAC   80.0       4.6      1.2
6        Jeremy Sochan         Poland   19  SAS   56.0       5.3      2.5
7       Malaki Branham  United States   19  SAS   66.0       2.7      1.9
8       Shaedon Sharpe         Canada   19  POR   80.0       3.0      1.2
9           Tari Eason  United States   21  HOU   82.0       6.0      1.1
10      Walker Kessler  United States   21  UTA   74.0       8.4      0.9
11         Jalen Duren  United States   19  DET   67.0       8.9      1.1
12       Mark Williams  United States   21  CHO   43.0       7.1      0.4
13          AJ Griffin  United States   19  ATL   72.0       2.1      1.0
14        Ochai Agbaji  United States   22  UTA   59.0       2.1      1.1
15         David Roddy  United States   21  MEM   70.0       2.8      0.8
16        Johnny Davis  United States   20  WAS   28.0       2.3      1.0
17        Nikola Jovic         Serbia   19  MIA   15.0       2.1      0.7
18    MarJon Beauchamp  United States   22  MIL   52.0       2.2      0.7
19        Blake Wesley  United States   19  SAS   37.0       2.2      2.7
20       Ousmane Dieng         France   19  OKC   39.0       2.7      1.2
21     Christian Braun  United States   21  DEN   76.0       2.4      0.8
22  TyTy Washington Jr  United States   21  HOU   31.0       1.5      1.5
23  Patrick Baldwin Jr  United States   20  GSW   31.0       1.3      0.4
24       Dyson Daniels      Australia   19  NOP   59.0       3.2      2.3
25       Peyton Watson  United States   20  DEN   23.0       1.6      0.5
26        Jake LaRavia  United States   21  MEM   35.0       1.8      0.6
27         Dalen Terry  United States   20  CHI   38.0       1.0      0.6
28    Wendell Moore Jr  United States   21  MIN   29.0       0.6      0.6

    Steals  Points per game  Round_x  Pick_x  Player Efficiency  \
0      0.8             20.0        1     1.0               14.9
1      0.6             16.7        1     6.0               13.1
2      0.8             16.3        1     5.0               12.1
3      1.4             14.1        1    12.0               15.6
4      0.5             12.8        1     3.0               11.2
5      0.8             12.2        1     4.0               12.3
6      0.8             11.0        1     9.0               11.4
7      0.5             10.2        1    20.0                9.5
8      0.5              9.9        1     7.0               11.5
9      1.2              9.3        1    17.0               15.2
10     0.4              9.2        1    22.0               21.5
11     0.7              9.1        1    13.0               17.3
12     0.7              9.0        1    15.0               19.8
13     0.6              8.9        1    16.0               12.6
14     0.3              7.9        1    14.0                9.5
15     0.4              6.7        1    23.0                8.8
16     0.4              5.8        1    10.0                7.2
17     0.5              5.5        1    27.0                NaN
18     0.4              5.1        1    24.0                8.2
19     0.7              5.0        1    25.0                3.5
20     0.4              4.9        1    11.0                9.3
21     0.5              4.7        1    21.0               10.3
22     0.5              4.7        1    29.0                7.5
23     0.2              3.9        1    28.0               11.3
24     0.7              3.8        1     8.0                8.8
25     0.1              3.3        1    30.0               12.8
26     0.3              3.0        1    19.0                6.7
27     0.3              2.2        1    18.0               14.1
28     0.3              1.4        1    26.0                9.3

    True Shooting  Win Shares  BPM  Round_y  Pick_y
0           0.529         2.4 -1.5      1.0     1.0
1           0.566         1.8 -3.7      1.0     6.0
2           0.528         0.0 -3.3      1.0     5.0
3           0.601         5.6  0.3      1.0    12.0
4           0.514         1.9 -3.7      1.0     3.0
5           0.597         4.3 -0.6      1.0     4.0
6           0.509         0.2 -4.0      1.0     9.0
7           0.524        -0.1 -5.2      1.0    20.0
8           0.568         1.2 -3.3      1.0     7.0
9           0.525         2.6 -1.7      1.0    17.0
10          0.702         7.1  2.9      1.0    22.0
11          0.655         4.5 -0.8      1.0    13.0
12          0.659         2.8  0.1      1.0    15.0
13          0.577         2.2 -0.8      1.0    16.0
14          0.561         1.3 -3.0      1.0    14.0
15          0.519         1.1 -3.9      1.0    23.0
16          0.446        -0.3 -7.4      1.0    10.0
17            NaN         NaN  NaN      NaN     NaN
18          0.513         0.4 -4.8      1.0    24.0
19          0.393        -1.6 -9.6      1.0    25.0
20          0.505         0.4 -3.6      1.0    11.0
21          0.568         1.9 -2.4      1.0    21.0
22          0.432        -0.1 -6.3      1.0    29.0
23          0.546         0.1 -2.1      1.0    28.0
24          0.503         1.3 -1.8      1.0     8.0
25          0.553         0.3 -2.8      1.0    30.0
26          0.531         0.5 -3.5      1.0    19.0
27          0.523         0.5  0.0      1.0    18.0
28          0.465         0.1 -2.4      1.0    26.0

In [158]:
nba22_rookie_stats.drop(['Round_x','Pick_x','Round_y','Pick_y'], axis=1, inplace=True)

In [191]:
nba22_rookie_stats.head()

,Player,Nationality,Age,Team,Games,Rebounds,Assists,Steals,Points per game,Player Efficiency,True Shooting,Win Shares,BPM
0,Paolo Banchero,United States,20,ORL,72.0,6.9,3.7,0.8,20.0,14.9,0.529,2.4,-1.5
1,Bennedict Mathurin,Canada,20,IND,78.0,4.1,1.5,0.6,16.7,13.1,0.566,1.8,-3.7
2,Jaden Ivey,United States,20,DET,74.0,3.9,5.2,0.8,16.3,12.1,0.528,0.0,-3.3
3,Jalen Williams,United States,21,OKC,75.0,4.5,3.3,1.4,14.1,15.6,0.601,5.6,0.3
4,Jabari Smith Jr,United States,19,HOU,79.0,7.2,1.3,0.5,12.8,11.2,0.514,1.9,-3.7

In [161]:
nba22_rookie_stats.loc[17, 'Player Efficiency'] = 10.6
nba22_rookie_stats.loc[17, 'True Shooting'] = .530
nba22_rookie_stats.loc[17, 'Win Shares'] = 0.2
nba22_rookie_stats.loc[17, 'BPM'] = -3.4

In [199]:
#data cleaning nba23_pergame_stats
data3=pd.read_csv('/Users/francescaparrella/analysis_projects/nba/nba23_pergame_stats.csv')
data3

,Player,Age,Team,Games,Rebounds,Assists,Steals,Points per game
0,Joel Embiid,29.0,PHI,39.0,11.0,5.6,1.2,34.7
1,Luka DonÄiÄ,24.0,DAL,70.0,9.2,9.8,1.4,33.9
2,Giannis Antetokounmpo,29.0,MIL,73.0,11.5,6.5,1.2,30.4
3,Shai Gilgeous-Alexander,25.0,OKC,75.0,5.5,6.2,2.0,30.1
4,Jalen Brunson,27.0,NYK,77.0,3.6,6.7,0.9,28.7
...,...,...,...,...,...,...,...,...
731,Ron Harper Jr.,23.0,TOR,1.0,0.0,1.0,0.0,0.0
732,Justin Jackson,28.0,MIN,2.0,0.0,0.0,0.0,0.0
733,Dmytro Skapintsev,25.0,NYK,2.0,0.0,0.0,0.0,0.0
734,Javonte Smart,24.0,PHI,1.0,0.0,0.0,0.0,0.0
735,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [165]:
data3.dtypes

Player              object
Age                float64
Team                object
Games              float64
Rebounds           float64
Assists            float64
Steals             float64
Points per game    float64
dtype: object

In [167]:
data3.isnull()

     Player    Age   Team  Games  Rebounds  Assists  Steals  Points per game
0     False  False  False  False     False    False   False            False
1     False  False  False  False     False    False   False            False
2     False  False  False  False     False    False   False            False
3     False  False  False  False     False    False   False            False
4     False  False  False  False     False    False   False            False
..      ...    ...    ...    ...       ...      ...     ...              ...
731   False  False  False  False     False    False   False            False
732   False  False  False  False     False    False   False            False
733   False  False  False  False     False    False   False            False
734   False  False  False  False     False    False   False            False
735   False   True   True   True      True     True    True             True

[736 rows x 8 columns]

In [168]:
rows=data3[data3.isnull().any(axis=1)]
print(rows)

             Player  Age Team  Games  Rebounds  Assists  Steals  \
735  League Average  NaN  NaN    NaN       NaN      NaN     NaN

     Points per game
735              NaN

In [172]:
data3.drop(index=735, inplace=True)

In [174]:
data3['Age'] = data3['Age'].astype(int)

In [176]:
data3.head()

,Player,Age,Team,Games,Rebounds,Assists,Steals,Points per game
0,Joel Embiid,29,PHI,39.0,11.0,5.6,1.2,34.7
1,Luka DonÄiÄ,24,DAL,70.0,9.2,9.8,1.4,33.9
2,Giannis Antetokounmpo,29,MIL,73.0,11.5,6.5,1.2,30.4
3,Shai Gilgeous-Alexander,25,OKC,75.0,5.5,6.2,2.0,30.1
4,Jalen Brunson,27,NYK,77.0,3.6,6.7,0.9,28.7

In [177]:
data3.loc[:,'Player'] = data3['Player'].str.replace('Ä', 'c')
print(data3[data3['Player'].str.contains('c')])

                Player  Age Team  Games  Rebounds  Assists  Steals  \
1        Luka Doncic   24  DAL   70.0       9.2      9.8     1.4
9     Donovan Mitchell   27  CLE   55.0       5.1      6.1     1.8
11       Nikola Jokic   28  DEN   79.0      12.4      9.0     1.4
29      Paolo Banchero   21  ORL   80.0       6.9      5.4     0.9
32   Jaren Jackson Jr.   24  MEM   66.0       5.5      2.3     1.2
..                 ...  ...  ...    ...       ...      ...     ...
723         Pete Nance   23  CLE    8.0       0.4      0.0     0.1
725   Ryan Arcidiacono   29  NYK   20.0       0.4      0.2     0.1
726    Malcolm Cazalon   22  DET    1.0       0.0      0.0     0.0
727     Jalen Crutcher   24  NOP    1.0       0.0      0.0     0.0
732     Justin Jackson   28  MIN    2.0       0.0      0.0     0.0

     Points per game
1               33.9
9               26.6
11              26.4
29              22.6
32              22.5
..               ...
723              0.4
725              0.0
726              0.0
727              0.0
732              0.0

[172 rows x 8 columns]

In [178]:
unwanted_car=['~','+','.','  ']

for char in unwanted_car: #i'm using a loop to iterate unwanted_car and format player for consistency
    data3.loc[:,'Player'] = data3['Player'].str.replace(char, '',regex=False)

In [187]:
data3['Player']=data3['Player'].str.replace('\u00A0',' ')

# Function to clean player names
def clean_player_name(name):
    # Replace specific unwanted characters
    name = name.replace('Ä', 'c')  # Example of replacing 'Ä' with 'c'
    # Remove any special characters using regex
    name = re.sub(r'[^\w\s]', '', name)  # This removes all non-word characters except spaces
    return name

# Apply the cleaning function to the 'Player' column
data3['Player'] = data3['Player'].apply(clean_player_name)

# Also strip any leading or trailing whitespace
data3['Player'] = data3['Player'].str.strip()

In [188]:
found=data3.loc[data3['Player'] == 'Nikola Jovic']
print(found)

           Player  Age Team  Games  Rebounds  Assists  Steals  Points per game
280  Nikola Jovic   20  MIA   46.0       4.2      2.0     0.5              7.7

In [192]:
filtered_data3= data3[data3['Player'].isin(df_rookie['Player'])]
#Merging filterd data with draft picks df to have the same 'player' column and add all the other columns of the df
nba23_pergame_rookie=filtered_data3.merge(df_rookie, on='Player', how='left')

In [195]:
cols=nba23_pergame_rookie.columns.tolist()
cols.insert(cols.index('Player') + 1, cols.pop(cols.index('Nationality')))
nba23_pergame_rookie=nba23_pergame_rookie[cols]

In [271]:
nba23_pergame_rookie.head(40)

,Player,Nationality,Age,Team,Games,Rebounds,Assists,Steals,Points per game,Round,Pick
0,Paolo Banchero,United States,21,ORL,80.0,6.9,5.4,0.9,22.6,1,1.0
1,Jalen Williams,United States,22,OKC,71.0,4.0,4.5,1.1,19.1,1,12.0
2,Chet Holmgren,United States,21,OKC,82.0,7.9,2.4,0.6,16.5,1,2.0
3,Shaedon Sharpe,Canada,20,POR,32.0,5.0,2.9,0.9,15.9,1,7.0
4,Jaden Ivey,United States,21,DET,77.0,3.4,3.8,0.7,15.4,1,5.0
5,Keegan Murray,United States,23,SAC,77.0,5.5,1.7,1.0,15.2,1,4.0
6,Bennedict Mathurin,Canada,21,IND,59.0,4.0,2.0,0.6,14.5,1,6.0
7,Jalen Duren,United States,20,DET,61.0,11.6,2.4,0.5,13.8,1,13.0
8,Jabari Smith Jr,United States,20,HOU,76.0,8.1,1.6,0.7,13.7,1,3.0
9,Mark Williams,United States,22,CHO,19.0,9.7,1.2,0.8,12.7,1,15.0
10,Jeremy Sochan,Poland,20,SAS,74.0,6.4,3.4,0.8,11.6,1,9.0
11,Jake LaRavia,United States,22,MEM,35.0,3.7,1.7,0.8,10.8,1,19.0
12,Tari Eason,United States,22,HOU,22.0,7.0,1.2,1.4,9.8,1,17.0
13,Malaki Branham,United States,20,SAS,75.0,2.0,2.1,0.4,9.2,1,20.0
14,Walker Kessler,United States,22,UTA,64.0,7.5,0.9,0.5,8.1,1,22.0
15,Nikola Jovic,Serbia,20,MIA,46.0,4.2,2.0,0.5,7.7,1,27.0
16,Christian Braun,United States,22,DEN,82.0,3.7,1.6,0.5,7.3,1,21.0
17,Peyton Watson,United States,21,DEN,80.0,3.2,1.1,0.5,6.7,1,30.0
18,David Roddy,United States,22,2TM,65.0,3.2,1.2,0.4,6.5,1,23.0
19,David Roddy,United States,22,MEM,48.0,4.2,1.6,0.5,8.4,1,23.0
20,David Roddy,United States,22,PHO,17.0,0.6,0.2,0.1,1.3,1,23.0
21,Ochai Agbaji,United States,23,2TM,78.0,2.8,1.1,0.6,5.8,1,14.0
22,Ochai Agbaji,United States,23,UTA,51.0,2.5,0.9,0.5,5.4,1,14.0
23,Ochai Agbaji,United States,23,TOR,27.0,3.3,1.3,0.7,6.7,1,14.0
24,Dyson Daniels,Australia,20,NOP,61.0,3.9,2.7,1.4,5.8,1,8.0
25,Patrick Baldwin Jr,United States,21,WAS,38.0,3.2,0.8,0.5,4.4,1,28.0
26,MarJon Beauchamp,United States,23,MIL,48.0,2.1,0.6,0.3,4.4,1,24.0
27,Blake Wesley,United States,20,SAS,61.0,1.5,2.7,0.5,4.4,1,25.0
28,Ousmane Dieng,France,20,OKC,33.0,1.5,1.1,0.2,4.0,1,11.0
29,Dalen Terry,United States,21,CHI,59.0,1.9,1.4,0.5,3.1,1,18.0
30,Johnny Davis,United States,21,WAS,50.0,1.4,0.6,0.4,3.0,1,10.0
31,AJ Griffin,United States,20,ATL,20.0,0.9,0.3,0.1,2.4,1,16.0
32,TyTy Washington Jr,United States,22,MIL,11.0,0.5,0.5,0.3,1.3,1,29.0
33,Wendell Moore Jr,United States,22,MIN,25.0,0.5,0.2,0.2,0.7,1,26.0

In [198]:
#data cleaning nba23_advanced_stats
data4=pd.read_csv('/Users/francescaparrella/analysis_projects/nba/nba23_advanced_stats_new.csv')
data4

,Player,Age,Team,Player Efficiency,True Shooting,Win Shares,BPM
0,Precious Achiuwa,24,TOT,14.6,0.545,3.4,-1.4
1,Precious Achiuwa,24,TOR,15.0,0.512,0.4,-1.6
2,Precious Achiuwa,24,NYK,14.5,0.564,3.0,-1.4
3,Bam Adebayo,26,MIA,19.8,0.576,7.2,2.4
4,Ochai Agbaji,23,TOT,7.7,0.497,0.1,-4.4
...,...,...,...,...,...,...,...
730,Thaddeus Young,35,PHO,15.1,0.515,0.3,-0.9
731,Trae Young,25,ATL,20.3,0.585,4.6,2.6
732,Omer Yurtseven,25,UTA,15.0,0.565,0.7,-3.0
733,Cody Zeller,31,NOP,12.8,0.483,0.8,-2.6
734,Ivica Zubac,26,LAC,19.3,0.671,6.8,0.8

In [201]:
data4.isnull()

     Player    Age   Team  Player Efficiency  True Shooting  Win Shares    BPM
0     False  False  False              False          False       False  False
1     False  False  False              False          False       False  False
2     False  False  False              False          False       False  False
3     False  False  False              False          False       False  False
4     False  False  False              False          False       False  False
..      ...    ...    ...                ...            ...         ...    ...
730   False  False  False              False          False       False  False
731   False  False  False              False          False       False  False
732   False  False  False              False          False       False  False
733   False  False  False              False          False       False  False
734   False  False  False              False          False       False  False

[735 rows x 7 columns]

In [202]:
row=data4[data4.isnull().any(axis=1)]
print(row)

              Player  Age Team  Player Efficiency  True Shooting  Win Shares  \
79    Marques Bolden   25  MIL                3.0            NaN         0.0
127  Malcolm Cazalon   22  DET                0.0            NaN         0.0
270   Ron Harper Jr.   23  TOR                0.0            NaN         0.0
321   Justin Jackson   28  MIN                0.0            NaN         0.0
330     Trey Jemison   24  WAS              -36.1            NaN         0.0
374   Kira Lewis Jr.   22  TOR               -7.3            NaN         0.0
517  Filip PetruÅ¡ev   23  PHI                4.0            NaN         0.0
607    Javonte Smart   24  PHI                0.0            NaN         0.0

      BPM
79   -5.5
127  -9.1
270  -8.8
321  -7.5
330 -33.9
374 -22.3
517  -4.9
607  -8.3

In [203]:
data4.dtypes

Player                object
Age                    int64
Team                  object
Player Efficiency    float64
True Shooting        float64
Win Shares           float64
BPM                  float64
dtype: object

In [205]:
unwanted_car=['~','+','.','  ']

for char in unwanted_car: #i'm using a loop to iterate unwanted_car and format player for consistency
    data4.loc[:,'Player'] = data4['Player'].str.replace(char, '',regex=False)

In [206]:
data4['Player']=data4['Player'].str.replace('\u00A0',' ')

# Function to clean player names
def clean_player_name(name):
    # Replace specific unwanted characters
    name = name.replace('Ä', 'c')  # Example of replacing 'Ä' with 'c'
    # Remove any special characters using regex
    name = re.sub(r'[^\w\s]', '', name)  # This removes all non-word characters except spaces
    return name

# Apply the cleaning function to the 'Player' column
data4['Player'] = data4['Player'].apply(clean_player_name)

# Also strip any leading or trailing whitespace
data4['Player'] = data4['Player'].str.strip()

In [209]:
name=data4.loc[data4['Player'] == 'Nikola Jovic']
print(name)

           Player  Age Team  Player Efficiency  True Shooting  Win Shares  BPM
350  Nikola Jovic   20  MIA               12.8          0.583         1.9  0.3

In [210]:
filtered_data4= data4[data4['Player'].isin(df_rookie['Player'])]
#Merging filterd data with draft picks df to have the same 'player' column and add all the other columns of the df
nba23_advanced_rookie=filtered_data4.merge(df_rookie, on='Player', how='left')

In [213]:
nba23_advanced_rookie.head()

,Player,Age,Team,Player Efficiency,True Shooting,Win Shares,BPM,Round,Pick,Nationality
0,Ochai Agbaji,23,TOT,7.7,0.497,0.1,-4.4,1,14.0,United States
1,Ochai Agbaji,23,UTA,8.1,0.531,0.4,-3.0,1,14.0,United States
2,Ochai Agbaji,23,TOR,7.1,0.453,-0.3,-6.5,1,14.0,United States
3,Patrick Baldwin Jr,21,WAS,9.7,0.502,0.2,-4.6,1,28.0,United States
4,Paolo Banchero,21,ORL,17.3,0.546,5.3,1.3,1,1.0,United States

In [214]:
cols=nba23_advanced_rookie.columns.tolist()
cols.insert(cols.index('Player') + 1, cols.pop(cols.index('Nationality')))
nba23_advanced_rookie=nba23_advanced_rookie[cols]

In [215]:
nba23_rookie_stats=pd.merge(nba23_pergame_rookie, nba23_advanced_rookie, on=['Age','Player','Team','Nationality'], how='outer')
print(nba23_rookie_stats)

                Player    Nationality  Age Team  Games  Rebounds  Assists  \
0       Paolo Banchero  United States   21  ORL   80.0       6.9      5.4
1       Jalen Williams  United States   22  OKC   71.0       4.0      4.5
2        Chet Holmgren  United States   21  OKC   82.0       7.9      2.4
3       Shaedon Sharpe         Canada   20  POR   32.0       5.0      2.9
4           Jaden Ivey  United States   21  DET   77.0       3.4      3.8
5        Keegan Murray  United States   23  SAC   77.0       5.5      1.7
6   Bennedict Mathurin         Canada   21  IND   59.0       4.0      2.0
7          Jalen Duren  United States   20  DET   61.0      11.6      2.4
8      Jabari Smith Jr  United States   20  HOU   76.0       8.1      1.6
9        Mark Williams  United States   22  CHO   19.0       9.7      1.2
10       Jeremy Sochan         Poland   20  SAS   74.0       6.4      3.4
11        Jake LaRavia  United States   22  MEM   35.0       3.7      1.7
12          Tari Eason  United States   22  HOU   22.0       7.0      1.2
13      Malaki Branham  United States   20  SAS   75.0       2.0      2.1
14      Walker Kessler  United States   22  UTA   64.0       7.5      0.9
15        Nikola Jovic         Serbia   20  MIA   46.0       4.2      2.0
16     Christian Braun  United States   22  DEN   82.0       3.7      1.6
17       Peyton Watson  United States   21  DEN   80.0       3.2      1.1
18         David Roddy  United States   22  2TM   65.0       3.2      1.2
19         David Roddy  United States   22  MEM   48.0       4.2      1.6
20         David Roddy  United States   22  PHO   17.0       0.6      0.2
21        Ochai Agbaji  United States   23  2TM   78.0       2.8      1.1
22        Ochai Agbaji  United States   23  UTA   51.0       2.5      0.9
23        Ochai Agbaji  United States   23  TOR   27.0       3.3      1.3
24       Dyson Daniels      Australia   20  NOP   61.0       3.9      2.7
25  Patrick Baldwin Jr  United States   21  WAS   38.0       3.2      0.8
26    MarJon Beauchamp  United States   23  MIL   48.0       2.1      0.6
27        Blake Wesley  United States   20  SAS   61.0       1.5      2.7
28       Ousmane Dieng         France   20  OKC   33.0       1.5      1.1
29         Dalen Terry  United States   21  CHI   59.0       1.9      1.4
30        Johnny Davis  United States   21  WAS   50.0       1.4      0.6
31          AJ Griffin  United States   20  ATL   20.0       0.9      0.3
32  TyTy Washington Jr  United States   22  MIL   11.0       0.5      0.5
33    Wendell Moore Jr  United States   22  MIN   25.0       0.5      0.2
34        Ochai Agbaji  United States   23  TOT    NaN       NaN      NaN
35         David Roddy  United States   22  TOT    NaN       NaN      NaN

    Steals  Points per game  Round_x  Pick_x  Player Efficiency  \
0      0.9             22.6      1.0     1.0               17.3
1      1.1             19.1      1.0    12.0               19.1
2      0.6             16.5      1.0     2.0               20.4
3      0.9             15.9      1.0     7.0               11.4
4      0.7             15.4      1.0     5.0               12.4
5      1.0             15.2      1.0     4.0               13.3
6      0.6             14.5      1.0     6.0               13.0
7      0.5             13.8      1.0    13.0               18.7
8      0.7             13.7      1.0     3.0               13.8
9      0.8             12.7      1.0    15.0               22.5
10     0.8             11.6      1.0     9.0               11.4
11     0.8             10.8      1.0    19.0               12.6
12     1.4              9.8      1.0    17.0               17.1
13     0.4              9.2      1.0    20.0                8.7
14     0.5              8.1      1.0    22.0               18.0
15     0.5              7.7      1.0    27.0               12.8
16     0.5              7.3      1.0    21.0               12.1
17     0.5              6.7      1.0    30.0               11.8
18     0.4              6.5      1.0    23.0                NaN
19     0.5              8.4      1.0    23.0                8.7
20     0.1              1.3      1.0    23.0                7.9
21     0.6              5.8      1.0    14.0                NaN
22     0.5              5.4      1.0    14.0                8.1
23     0.7              6.7      1.0    14.0                7.1
24     1.4              5.8      1.0     8.0               12.0
25     0.5              4.4      1.0    28.0                9.7
26     0.3              4.4      1.0    24.0                9.7
27     0.5              4.4      1.0    25.0               10.1
28     0.2              4.0      1.0    11.0               10.1
29     0.5              3.1      1.0    18.0               10.2
30     0.4              3.0      1.0    10.0                6.2
31     0.1              2.4      1.0    16.0                1.2
32     0.3              1.3      1.0    29.0                4.6
33     0.2              0.7      1.0    26.0                8.6
34     NaN              NaN      NaN     NaN                7.7
35     NaN              NaN      NaN     NaN                8.7

    True Shooting  Win Shares  BPM  Round_y  Pick_y
0           0.546         5.3  1.3      1.0     1.0
1           0.621         7.3  2.3      1.0    12.0
2           0.632         8.9  3.4      1.0     2.0
3           0.524         0.5 -2.8      1.0     7.0
4           0.536         0.5 -3.1      1.0     5.0
5           0.569         5.2 -0.9      1.0     4.0
6           0.562         1.4 -3.4      1.0     6.0
7           0.653         4.8 -0.1      1.0    13.0
8           0.571         5.6 -0.4      1.0     3.0
9           0.675         2.1  0.8      1.0    15.0
10          0.513         1.4 -3.4      1.0     9.0
11          0.540         1.0 -2.5      1.0    19.0
12          0.528         1.3  1.6      1.0    17.0
13          0.526        -0.3 -5.6      1.0    20.0
14          0.663         4.1  0.9      1.0    22.0
15          0.583         1.9  0.3      1.0    27.0
16          0.554         3.4 -1.9      1.0    21.0
17          0.539         2.5 -2.2      1.0    30.0
18            NaN         NaN  NaN      NaN     NaN
19          0.485         0.1 -5.0      1.0    23.0
20          0.469         0.0 -5.8      1.0    23.0
21            NaN         NaN  NaN      NaN     NaN
22          0.531         0.4 -3.0      1.0    14.0
23          0.453        -0.3 -6.5      1.0    14.0
24          0.529         2.9  0.6      1.0     8.0
25          0.502         0.2 -4.6      1.0    28.0
26          0.592         0.7 -3.2      1.0    24.0
27          0.537         0.9 -4.0      1.0    25.0
28          0.540         0.4 -3.0      1.0    11.0
29          0.512         0.8 -2.3      1.0    18.0
30          0.462        -0.1 -6.6      1.0    10.0
31          0.382        -0.4 -9.6      1.0    16.0
32          0.350        -0.1 -8.2      1.0    29.0
33          0.500         0.1 -2.8      1.0    26.0
34          0.497         0.1 -4.4      1.0    14.0
35          0.484         0.1 -5.0      1.0    23.0

In [218]:
nba23_rookie_stats.drop(['Round_x','Pick_x','Round_y','Pick_y'], axis=1, inplace=True)
nba23_rookie_stats.head()

,Player,Nationality,Age,Team,Games,Rebounds,Assists,Steals,Points per game,Player Efficiency,True Shooting,Win Shares,BPM
0,Paolo Banchero,United States,21,ORL,80.0,6.9,5.4,0.9,22.6,17.3,0.546,5.3,1.3
1,Jalen Williams,United States,22,OKC,71.0,4.0,4.5,1.1,19.1,19.1,0.621,7.3,2.3
2,Chet Holmgren,United States,21,OKC,82.0,7.9,2.4,0.6,16.5,20.4,0.632,8.9,3.4
3,Shaedon Sharpe,Canada,20,POR,32.0,5.0,2.9,0.9,15.9,11.4,0.524,0.5,-2.8
4,Jaden Ivey,United States,21,DET,77.0,3.4,3.8,0.7,15.4,12.4,0.536,0.5,-3.1

In [217]:
nba22_rookie_stats.head()

,Player,Nationality,Age,Team,Games,Rebounds,Assists,Steals,Points per game,Player Efficiency,True Shooting,Win Shares,BPM
0,Paolo Banchero,United States,20,ORL,72.0,6.9,3.7,0.8,20.0,14.9,0.529,2.4,-1.5
1,Bennedict Mathurin,Canada,20,IND,78.0,4.1,1.5,0.6,16.7,13.1,0.566,1.8,-3.7
2,Jaden Ivey,United States,20,DET,74.0,3.9,5.2,0.8,16.3,12.1,0.528,0.0,-3.3
3,Jalen Williams,United States,21,OKC,75.0,4.5,3.3,1.4,14.1,15.6,0.601,5.6,0.3
4,Jabari Smith Jr,United States,19,HOU,79.0,7.2,1.3,0.5,12.8,11.2,0.514,1.9,-3.7

In [231]:
#data cleaning nba22_rookie_value
data6=pd.read_csv('/Users/francescaparrella/analysis_projects/nba/nba22_rookie_value.csv')
data6

,Player,Years Contract,Value,Average Annual Value
0,Paolo Banchero,4,"$50,158,769","$12,539,692"
1,Chet Holmgren,4,"$44,889,248","$11,222,312"
2,Jabari Smith Jr.,4,"$40,330,432","$10,082,608"
3,Keegan Murray,4,"$36,371,093","$9,092,773"
4,Jaden Ivey,4,"$32,951,083","$8,237,771"
5,Bennedict Mathurin,4,"$29,936,173","$7,484,043"
6,Shaedon Sharpe,4,"$27,340,903","$6,835,226"
7,Dyson Daniels,4,"$25,059,949","$6,264,987"
8,Jeremy Sochan,4,"$23,046,751","$5,761,688"
9,Johnny Davis,4,"$21,898,509","$5,474,627"
10,Ousmane Dieng,4,"$21,066,202","$5,266,551"
11,Jalen Williams,4,"$20,256,917","$5,064,229"
12,Jalen Duren,4,"$19,474,944","$4,868,736"
13,Ochai Agbaji,4,"$18,726,365","$4,681,591"
14,Mark Williams,4,"$18,001,011","$4,500,253"
15,A.J. Griffin,4,"$17,106,137","$4,276,534"
16,Tari Eason,4,"$16,257,246","$4,064,312"
17,Dalen Terry,4,"$15,451,758","$3,862,940"
18,Jake LaRavia,4,"$14,763,367","$3,690,842"
19,Malaki Branham,4,"$14,177,433","$3,544,358"
20,Christian Braun,4,"$13,769,157","$3,442,289"
21,Walker Kessler,4,"$13,372,418","$3,343,105"
22,David Roddy,4,"$12,985,886","$3,246,472"
23,MarJon Beauchamp,4,"$12,609,596","$3,152,399"
24,Blake Wesley,4,"$12,240,728","$3,060,182"
25,Wendell Moore Jr.,4,"$11,839,563","$2,959,891"
26,Nikola Jovic,4,"$11,501,537","$2,875,384"
27,Patrick Baldwin Jr.,4,"$13,993,276","$3,498,319"
28,TyTy Washington Jr.,4,"$11,349,659","$2,837,415"
29,Peyton Watson,4,"$11,267,516","$2,816,879"
30,Andrew Nembhard,4,"$8,583,166","$2,145,792"
31,Caleb Houstan,4,"$8,207,398","$2,051,850"
32,Christian Koloko,3,"$5,239,563","$1,746,521"
33,Jaylin Williams,4,"$8,207,398","$2,051,850"
34,Max Christie,2,"$2,737,645","$1,368,823"
35,Gabriele Procida,- \n ...,-,-
36,Jaden Hardy,3,"$4,757,344","$1,585,781"
37,Kennedy Chandler,4,"$7,127,014","$1,781,754"
38,Khalifa Diop,- \n ...,-,-
39,Bryce McGowens,1,-,-
40,E.J. Liddell,2,-,-
41,Trevor Keels,1,-,-
42,Moussa Diabate,1,-,-
43,Ryan Rollins,3,"$4,757,344","$1,585,781"
44,Josh Minott,4,"$6,944,795","$1,736,199"
45,Ismael Kamagate,- \n ...,-,-
46,Vincent Williams Jr.,2,-,-
47,Kendall Brown,1,-,-
48,Isaiah Mobley,1,-,-
49,Matteo Spagnolo,- \n ...,-,-
50,Forfeit,-,-,-
51,Forfeit,-,-,-
52,Tyrese Martin,2,"$2,737,645","$1,368,823"
53,Karlo Matkovic,3,"$5,408,801","$1,802,934"
54,J.D. Davison,1,-,-
55,Yannick Nzosa,- \n ...,-,-
56,Gui Santos,3,"$5,143,017","$1,714,339"
57,Luke Travers,1,-,-
58,Jabari Walker,3,"$4,757,344","$1,585,781"
59,Hugo Besson,- \n ...,-,-

In [221]:
data5.dtypes

Player                  object
Years Contract          object
Value                   object
Average Annual Value    object
dtype: object

In [232]:
row=data6[data6.isnull().any(axis=1)]
print(row)

Empty DataFrame
Columns: [Player, Years Contract, Value, Average Annual Value]
Index: []

In [233]:
unwanted_car=['~','+','.','  ']

for char in unwanted_car: #i'm using a loop to iterate unwanted_car and format player for consistency
    data6.loc[:,'Player'] = data6['Player'].str.replace(char, '',regex=False)

In [235]:
name=data6[data6['Player'] == 'Nikola Jovic']
print(name)

          Player Years Contract        Value Average Annual Value
26  Nikola Jovic              4  $11,501,537           $2,875,384

In [238]:
filtered_data6= data6[data6['Player'].isin(df_rookie['Player'])]
#Merging filterd data with draft picks df to have the same 'player' column and add all the other columns of the df
nba22_rookie_value=filtered_data6.merge(df_rookie, on='Player', how='left')

In [240]:
cols=nba22_rookie_value.columns.tolist()
cols.insert(cols.index('Player') + 1, cols.pop(cols.index('Nationality')))
nba22_rookie_value=nba22_rookie_value[cols]

In [242]:
nba22_rookie_value.dtypes

Player                   object
Nationality              object
Years Contract           object
Value                    object
Average Annual Value     object
Round                     int64
Pick                    float64
dtype: object

In [243]:
nba22_rookie_value['Years Contract'] = nba22_rookie_value['Years Contract'].astype(int)

In [248]:
print("Original DataFrame:")
print(nba22_rookie_value)

# Function to clean and convert dollar values to float
def clean_and_convert(value):
    if isinstance(value, str):  # Check if the value is a string
        value = value.replace('$', '')  # Remove dollar sign
        value = value.replace(',', '')  # Remove commas
        return value.strip()  # Trim whitespace
    return value  # Return non-string values as they are

nba22_rookie_value[['Value', 'Average Annual Value']] = nba22_rookie_value[['Value', 'Average Annual Value']].applymap(clean_and_convert)

# Convert the cleaned values to float for both columns
nba22_rookie_value[['Value', 'Average Annual Value']] = nba22_rookie_value[['Value', 'Average Annual Value']].apply(pd.to_numeric, errors='coerce')

# Display the modified DataFrame
print("\nModified DataFrame:")
print(nba22_rookie_value)

Original DataFrame:
                Player    Nationality  Years Contract        Value  \
0       Paolo Banchero  United States               4  $50,158,769
1        Chet Holmgren  United States               4  $44,889,248
2      Jabari Smith Jr  United States               4  $40,330,432
3        Keegan Murray  United States               4  $36,371,093
4           Jaden Ivey  United States               4  $32,951,083
5   Bennedict Mathurin         Canada               4  $29,936,173
6       Shaedon Sharpe         Canada               4  $27,340,903
7        Dyson Daniels      Australia               4  $25,059,949
8        Jeremy Sochan         Poland               4  $23,046,751
9         Johnny Davis  United States               4  $21,898,509
10       Ousmane Dieng         France               4  $21,066,202
11      Jalen Williams  United States               4  $20,256,917
12         Jalen Duren  United States               4  $19,474,944
13        Ochai Agbaji  United States               4  $18,726,365
14       Mark Williams  United States               4  $18,001,011
15          AJ Griffin  United States               4  $17,106,137
16          Tari Eason  United States               4  $16,257,246
17         Dalen Terry  United States               4  $15,451,758
18        Jake LaRavia  United States               4  $14,763,367
19      Malaki Branham  United States               4  $14,177,433
20     Christian Braun  United States               4  $13,769,157
21      Walker Kessler  United States               4  $13,372,418
22         David Roddy  United States               4  $12,985,886
23    MarJon Beauchamp  United States               4  $12,609,596
24        Blake Wesley  United States               4  $12,240,728
25    Wendell Moore Jr  United States               4  $11,839,563
26        Nikola Jovic         Serbia               4  $11,501,537
27  Patrick Baldwin Jr  United States               4  $13,993,276
28  TyTy Washington Jr  United States               4  $11,349,659
29       Peyton Watson  United States               4  $11,267,516

   Average Annual Value  Round  Pick
0           $12,539,692      1   1.0
1           $11,222,312      1   2.0
2           $10,082,608      1   3.0
3            $9,092,773      1   4.0
4            $8,237,771      1   5.0
5            $7,484,043      1   6.0
6            $6,835,226      1   7.0
7            $6,264,987      1   8.0
8            $5,761,688      1   9.0
9            $5,474,627      1  10.0
10           $5,266,551      1  11.0
11           $5,064,229      1  12.0
12           $4,868,736      1  13.0
13           $4,681,591      1  14.0
14           $4,500,253      1  15.0
15           $4,276,534      1  16.0
16           $4,064,312      1  17.0
17           $3,862,940      1  18.0
18           $3,690,842      1  19.0
19           $3,544,358      1  20.0
20           $3,442,289      1  21.0
21           $3,343,105      1  22.0
22           $3,246,472      1  23.0
23           $3,152,399      1  24.0
24           $3,060,182      1  25.0
25           $2,959,891      1  26.0
26           $2,875,384      1  27.0
27           $3,498,319      1  28.0
28           $2,837,415      1  29.0
29           $2,816,879      1  30.0

Modified DataFrame:
                Player    Nationality  Years Contract     Value  \
0       Paolo Banchero  United States               4  50158769
1        Chet Holmgren  United States               4  44889248
2      Jabari Smith Jr  United States               4  40330432
3        Keegan Murray  United States               4  36371093
4           Jaden Ivey  United States               4  32951083
5   Bennedict Mathurin         Canada               4  29936173
6       Shaedon Sharpe         Canada               4  27340903
7        Dyson Daniels      Australia               4  25059949
8        Jeremy Sochan         Poland               4  23046751
9         Johnny Davis  United States               4  21898509
10       Ousmane Dieng         France               4  21066202
11      Jalen Williams  United States               4  20256917
12         Jalen Duren  United States               4  19474944
13        Ochai Agbaji  United States               4  18726365
14       Mark Williams  United States               4  18001011
15          AJ Griffin  United States               4  17106137
16          Tari Eason  United States               4  16257246
17         Dalen Terry  United States               4  15451758
18        Jake LaRavia  United States               4  14763367
19      Malaki Branham  United States               4  14177433
20     Christian Braun  United States               4  13769157
21      Walker Kessler  United States               4  13372418
22         David Roddy  United States               4  12985886
23    MarJon Beauchamp  United States               4  12609596
24        Blake Wesley  United States               4  12240728
25    Wendell Moore Jr  United States               4  11839563
26        Nikola Jovic         Serbia               4  11501537
27  Patrick Baldwin Jr  United States               4  13993276
28  TyTy Washington Jr  United States               4  11349659
29       Peyton Watson  United States               4  11267516

    Average Annual Value  Round  Pick
0               12539692      1   1.0
1               11222312      1   2.0
2               10082608      1   3.0
3                9092773      1   4.0
4                8237771      1   5.0
5                7484043      1   6.0
6                6835226      1   7.0
7                6264987      1   8.0
8                5761688      1   9.0
9                5474627      1  10.0
10               5266551      1  11.0
11               5064229      1  12.0
12               4868736      1  13.0
13               4681591      1  14.0
14               4500253      1  15.0
15               4276534      1  16.0
16               4064312      1  17.0
17               3862940      1  18.0
18               3690842      1  19.0
19               3544358      1  20.0
20               3442289      1  21.0
21               3343105      1  22.0
22               3246472      1  23.0
23               3152399      1  24.0
24               3060182      1  25.0
25               2959891      1  26.0
26               2875384      1  27.0
27               3498319      1  28.0
28               2837415      1  29.0
29               2816879      1  30.0

In [249]:
nba22_rookie_value.dtypes

Player                   object
Nationality              object
Years Contract            int64
Value                     int64
Average Annual Value      int64
Round                     int64
Pick                    float64
dtype: object

In [250]:
nba22_rookie_value.head()

,Player,Nationality,Years Contract,Value,Average Annual Value,Round,Pick
0,Paolo Banchero,United States,4,50158769,12539692,1,1.0
1,Chet Holmgren,United States,4,44889248,11222312,1,2.0
2,Jabari Smith Jr,United States,4,40330432,10082608,1,3.0
3,Keegan Murray,United States,4,36371093,9092773,1,4.0
4,Jaden Ivey,United States,4,32951083,8237771,1,5.0

In [252]:
nba22_rookie_value.drop(['Pick'], axis=1, inplace=True)

In [255]:
nba22_rookie_value.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Player                30 non-null     object
 1   Nationality           30 non-null     object
 2   Years Contract        30 non-null     int64
 3   Value                 30 non-null     int64
 4   Average Annual Value  30 non-null     int64
 5   Round                 30 non-null     int64
dtypes: int64(4), object(2)
memory usage: 1.5+ KB

In [266]:
cols = list(nba22_rookie_value.columns)

# Remove 'Round' from the current list of columns
cols.remove('Round')

# Insert 'Round' before 'Player'
player_index = cols.index('Player')
cols.insert(player_index, 'Round')

# Rearrange the DataFrame with the new column order
nba22_rookie_value = nba22_rookie_value[cols]

# Display the modified DataFrame
print(nba22_rookie_value)

    Round              Player    Nationality  Years Contract     Value  \
0       1      Paolo Banchero  United States               4  50158769
1       1       Chet Holmgren  United States               4  44889248
2       1     Jabari Smith Jr  United States               4  40330432
3       1       Keegan Murray  United States               4  36371093
4       1          Jaden Ivey  United States               4  32951083
5       1  Bennedict Mathurin         Canada               4  29936173
6       1      Shaedon Sharpe         Canada               4  27340903
7       1       Dyson Daniels      Australia               4  25059949
8       1       Jeremy Sochan         Poland               4  23046751
9       1        Johnny Davis  United States               4  21898509
10      1       Ousmane Dieng         France               4  21066202
11      1      Jalen Williams  United States               4  20256917
12      1         Jalen Duren  United States               4  19474944
13      1        Ochai Agbaji  United States               4  18726365
14      1       Mark Williams  United States               4  18001011
15      1          AJ Griffin  United States               4  17106137
16      1          Tari Eason  United States               4  16257246
17      1         Dalen Terry  United States               4  15451758
18      1        Jake LaRavia  United States               4  14763367
19      1      Malaki Branham  United States               4  14177433
20      1     Christian Braun  United States               4  13769157
21      1      Walker Kessler  United States               4  13372418
22      1         David Roddy  United States               4  12985886
23      1    MarJon Beauchamp  United States               4  12609596
24      1        Blake Wesley  United States               4  12240728
25      1    Wendell Moore Jr  United States               4  11839563
26      1        Nikola Jovic         Serbia               4  11501537
27      1  Patrick Baldwin Jr  United States               4  13993276
28      1  TyTy Washington Jr  United States               4  11349659
29      1       Peyton Watson  United States               4  11267516

    Average Annual Value
0               12539692
1               11222312
2               10082608
3                9092773
4                8237771
5                7484043
6                6835226
7                6264987
8                5761688
9                5474627
10               5266551
11               5064229
12               4868736
13               4681591
14               4500253
15               4276534
16               4064312
17               3862940
18               3690842
19               3544358
20               3442289
21               3343105
22               3246472
23               3152399
24               3060182
25               2959891
26               2875384
27               3498319
28               2837415
29               2816879

In [267]:
nba22_rookie_value.head()

,Round,Player,Nationality,Years Contract,Value,Average Annual Value
0,1,Paolo Banchero,United States,4,50158769,12539692
1,1,Chet Holmgren,United States,4,44889248,11222312
2,1,Jabari Smith Jr,United States,4,40330432,10082608
3,1,Keegan Murray,United States,4,36371093,9092773
4,1,Jaden Ivey,United States,4,32951083,8237771

In [268]:
#save df into csv
nba22_rookie_stats.to_csv('nba22_rookie_stats.csv', index=False)
nba23_rookie_stats.to_csv('nba23_rookie_stats.csv', index=False)
nba22_rookie_value.to_csv('nba22_rookie_value.csv', index=False)
df_rookie.to_csv('df_rookie.csv', index=False)

print('did it')

did it

In [273]:
nba23_rookie_stats.head(40)

,Player,Nationality,Age,Team,Games,Rebounds,Assists,Steals,Points per game,Player Efficiency,True Shooting,Win Shares,BPM
0,Paolo Banchero,United States,21,ORL,80.0,6.9,5.4,0.9,22.6,17.3,0.546,5.3,1.3
1,Jalen Williams,United States,22,OKC,71.0,4.0,4.5,1.1,19.1,19.1,0.621,7.3,2.3
2,Chet Holmgren,United States,21,OKC,82.0,7.9,2.4,0.6,16.5,20.4,0.632,8.9,3.4
3,Shaedon Sharpe,Canada,20,POR,32.0,5.0,2.9,0.9,15.9,11.4,0.524,0.5,-2.8
4,Jaden Ivey,United States,21,DET,77.0,3.4,3.8,0.7,15.4,12.4,0.536,0.5,-3.1
5,Keegan Murray,United States,23,SAC,77.0,5.5,1.7,1.0,15.2,13.3,0.569,5.2,-0.9
6,Bennedict Mathurin,Canada,21,IND,59.0,4.0,2.0,0.6,14.5,13.0,0.562,1.4,-3.4
7,Jalen Duren,United States,20,DET,61.0,11.6,2.4,0.5,13.8,18.7,0.653,4.8,-0.1
8,Jabari Smith Jr,United States,20,HOU,76.0,8.1,1.6,0.7,13.7,13.8,0.571,5.6,-0.4
9,Mark Williams,United States,22,CHO,19.0,9.7,1.2,0.8,12.7,22.5,0.675,2.1,0.8
10,Jeremy Sochan,Poland,20,SAS,74.0,6.4,3.4,0.8,11.6,11.4,0.513,1.4,-3.4
11,Jake LaRavia,United States,22,MEM,35.0,3.7,1.7,0.8,10.8,12.6,0.540,1.0,-2.5
12,Tari Eason,United States,22,HOU,22.0,7.0,1.2,1.4,9.8,17.1,0.528,1.3,1.6
13,Malaki Branham,United States,20,SAS,75.0,2.0,2.1,0.4,9.2,8.7,0.526,-0.3,-5.6
14,Walker Kessler,United States,22,UTA,64.0,7.5,0.9,0.5,8.1,18.0,0.663,4.1,0.9
15,Nikola Jovic,Serbia,20,MIA,46.0,4.2,2.0,0.5,7.7,12.8,0.583,1.9,0.3
16,Christian Braun,United States,22,DEN,82.0,3.7,1.6,0.5,7.3,12.1,0.554,3.4,-1.9
17,Peyton Watson,United States,21,DEN,80.0,3.2,1.1,0.5,6.7,11.8,0.539,2.5,-2.2
18,David Roddy,United States,22,2TM,65.0,3.2,1.2,0.4,6.5,NaN,NaN,NaN,NaN
19,David Roddy,United States,22,MEM,48.0,4.2,1.6,0.5,8.4,8.7,0.485,0.1,-5.0
20,David Roddy,United States,22,PHO,17.0,0.6,0.2,0.1,1.3,7.9,0.469,0.0,-5.8
21,Ochai Agbaji,United States,23,2TM,78.0,2.8,1.1,0.6,5.8,NaN,NaN,NaN,NaN
22,Ochai Agbaji,United States,23,UTA,51.0,2.5,0.9,0.5,5.4,8.1,0.531,0.4,-3.0
23,Ochai Agbaji,United States,23,TOR,27.0,3.3,1.3,0.7,6.7,7.1,0.453,-0.3,-6.5
24,Dyson Daniels,Australia,20,NOP,61.0,3.9,2.7,1.4,5.8,12.0,0.529,2.9,0.6
25,Patrick Baldwin Jr,United States,21,WAS,38.0,3.2,0.8,0.5,4.4,9.7,0.502,0.2,-4.6
26,MarJon Beauchamp,United States,23,MIL,48.0,2.1,0.6,0.3,4.4,9.7,0.592,0.7,-3.2
27,Blake Wesley,United States,20,SAS,61.0,1.5,2.7,0.5,4.4,10.1,0.537,0.9,-4.0
28,Ousmane Dieng,France,20,OKC,33.0,1.5,1.1,0.2,4.0,10.1,0.540,0.4,-3.0
29,Dalen Terry,United States,21,CHI,59.0,1.9,1.4,0.5,3.1,10.2,0.512,0.8,-2.3
30,Johnny Davis,United States,21,WAS,50.0,1.4,0.6,0.4,3.0,6.2,0.462,-0.1,-6.6
31,AJ Griffin,United States,20,ATL,20.0,0.9,0.3,0.1,2.4,1.2,0.382,-0.4,-9.6
32,TyTy Washington Jr,United States,22,MIL,11.0,0.5,0.5,0.3,1.3,4.6,0.350,-0.1,-8.2
33,Wendell Moore Jr,United States,22,MIN,25.0,0.5,0.2,0.2,0.7,8.6,0.500,0.1,-2.8
34,Ochai Agbaji,United States,23,TOT,NaN,NaN,NaN,NaN,NaN,7.7,0.497,0.1,-4.4
35,David Roddy,United States,22,TOT,NaN,NaN,NaN,NaN,NaN,8.7,0.484,0.1,-5.0

In [275]:
nba23_rookie_stats.drop([21, 23, 18, 20,34 ,35], axis=0, inplace=True)

In [277]:
nba23_rookie_stats.reset_index(drop=True, inplace=True)

In [278]:
nba23_rookie_stats.to_csv('nba23_rookie_stats_correct.csv', index=False)